# Generated by Django 5.0.1 on 2024-03-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregdb',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
