# Generated by Django 5.0.1 on 2024-03-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psyapp', '0002_pregdb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregdb',
            name='pexp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pregdb',
            name='pgen',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pregdb',
            name='pqual',
            field=models.CharField(default='', max_length=30),
        ),
    ]
