# Generated by Django 5.0.1 on 2024-04-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psyapp', '0003_pregdb_pexp_pregdb_pgen_pregdb_pqual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregdb',
            name='pexp',
        ),
        migrations.RemoveField(
            model_name='pregdb',
            name='pgen',
        ),
        migrations.RemoveField(
            model_name='pregdb',
            name='pprf',
        ),
        migrations.RemoveField(
            model_name='pregdb',
            name='ppsw',
        ),
        migrations.RemoveField(
            model_name='pregdb',
            name='pqual',
        ),
        migrations.RemoveField(
            model_name='pregdb',
            name='status',
        ),
    ]
