# Generated by Django 5.0.1 on 2024-04-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psyapp', '0005_pregdb_pexp_pregdb_pgen_pregdb_pprf_pregdb_ppsw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregdb',
            name='ppsw',
            field=models.TextField(),
        ),
    ]
