# Generated by Django 5.0.1 on 2024-04-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psyapp', '0006_alter_pregdb_ppsw'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregdb',
            name='rid',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
