# Generated by Django 5.0.1 on 2024-04-11 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psyapp', '0007_pregdb_rid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregdb',
            name='rid',
        ),
    ]
