# Generated by Django 5.0.1 on 2024-03-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='atregdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atname', models.CharField(max_length=30)),
                ('atmail', models.EmailField(max_length=254)),
                ('atprf', models.ImageField(default='null.jpg', upload_to='atregimgs')),
                ('atpsw', models.TextField()),
            ],
        ),
    ]
