# Generated by Django 5.0.1 on 2024-03-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('cmail', models.EmailField(max_length=254)),
                ('cmsg', models.TextField()),
            ],
        ),
    ]
