# Generated by Django 5.0.1 on 2024-03-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_contdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='contdb',
            name='csub',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
