# Generated by Django 5.0.1 on 2024-04-02 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psyapp', '0003_pregdb_pexp_pregdb_pgen_pregdb_pqual'),
        ('userapp', '0003_contdb_csub'),
    ]

    operations = [
        migrations.CreateModel(
            name='psyapn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('sub', models.CharField(max_length=40)),
                ('dte', models.DateField()),
                ('tme', models.TimeField()),
                ('status', models.IntegerField(default=0)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psyapp.pregdb')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.regdb')),
            ],
        ),
    ]
