# Generated by Django 5.0.1 on 2024-04-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_atapn'),
    ]

    operations = [
        migrations.AddField(
            model_name='psyapn',
            name='rid',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
