# Generated by Django 5.0.1 on 2024-04-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_topic_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply',
            new_name='rep',
        ),
    ]
